name: development-actions

on:
  push:
    branches-ignore:
      - master
      - main
      - 'wip*'
      - '[0-9]+.[0-9x]+.x'
jobs:
  ci:
    name: run style verification and publish to nexus staging repository
    runs-on: ubuntu-22.04
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Java JDK 11 setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          architecture: x64
          distribution: 'zulu'
          cache: 'maven'
          server-id: ossrh
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Run tests and style checks
        run: ./mvnw clean verify

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Snapshot repository
        run: ./mvnw deploy -Dmaven.test.skip=true -Dcheckstyle.skip=true -Ddetekt.skip=true
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}



