name: multi-platform-ci

on:
  push:
    branches:
      - main
      - master

jobs:
  ci:
    name: publish to maven-central
    runs-on: ubuntu-20.04
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Java JDK 11 setup
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
          architecture: x64