name: multi-platform-ci

on:
  push:
    branches-ignore:
      - master
      - main
      - wip*
jobs:
  ci:
    name: run style verification and publish to nexus staging repository
    runs-on: ubuntu-20.04
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Java JDK 11 setup
        uses: actions/setup-java@v3
        with:
          java-version: 11
          architecture: x64
          distribution: 'zulu'

      - name: Run style checks
        run: ./mvnw clean verify

      - name: Setup Maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.NEXUS_USERNAME }}", "password": "${{ secrets.NEXUS_PASSWORD }}" }]'

      - name: Publish to Staging repository
        run: ./mvnw deploy

